#!/usr/bin/with-contenv bash

PAPERLESS_REDIS=${REDIS_URL:-redis://localhost:6379}

# remove services unless they're enabled
if [[ -v "REDIS_URL" ]]; then
    rm -rf /etc/services.d/redis
fi

mkdir -p \
    /config \
    /data \
    /data/media \
    /data/consume

mv /defaults/uwsgi.ini /app/paperless/src/uwsgi.ini > /dev/null 2>&1
cp /defaults/imagemagick-policy.xml /etc/ImageMagick-6/policy.xml

# permissions
chown -R abc:abc \
    /app/paperless \
    /config \
    /data
