#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend switching to the new official container: 
https://github.com/paperless-ngx/paperless-ngx


******************************************************
******************************************************'
